"""Chapter 2 reference solutions.

Used by tests/conftest.py to expose each function/class as a pytest fixture so the
same test bodies grade either (a) what the student wrote in the notebook, via
`judge.check(fn)`, or (b) this reference module, via `pytest tests/test_chapter_02.py`.

Students do not edit this file directly — they implement in the notebook.
"""
from __future__ import annotations

import functools

import jax
import jax.numpy as jnp
import equinox as eqx
import optax
from jax.sharding import Mesh, PartitionSpec as P, NamedSharding


def sinusoidal_positions(max_seq: int, dim: int) -> jax.Array:
    """Standard 'Attention is All You Need' positional table of shape (max_seq, dim)."""
    pos = jnp.arange(max_seq)[:, None]
    i = jnp.arange(0, dim, 2)[None, :]
    angle_rates = 1 / (10000 ** (i / dim))
    angles = pos * angle_rates
    pe = jnp.zeros((max_seq, dim))
    pe = pe.at[:, 0::2].set(jnp.sin(angles))
    pe = pe.at[:, 1::2].set(jnp.cos(angles))
    return pe


class Block(eqx.Module):
    attn: eqx.nn.MultiheadAttention
    mlp_in: eqx.nn.Linear
    mlp_out: eqx.nn.Linear
    ln1: eqx.nn.LayerNorm
    ln2: eqx.nn.LayerNorm

    def __init__(self, embed_dim: int, num_heads: int, *, key):
        k1, k2, k3 = jax.random.split(key, 3)
        self.attn = eqx.nn.MultiheadAttention(
            num_heads=num_heads, query_size=embed_dim, inference=True, key=k1,
        )
        self.mlp_in = eqx.nn.Linear(embed_dim, 4 * embed_dim, key=k2)
        self.mlp_out = eqx.nn.Linear(4 * embed_dim, embed_dim, key=k3)
        self.ln1 = eqx.nn.LayerNorm(embed_dim)
        self.ln2 = eqx.nn.LayerNorm(embed_dim)

    def __call__(self, x_SxE: jax.Array, *, key=None) -> jax.Array:
        S = x_SxE.shape[0]
        mask_SxS = jnp.tril(jnp.ones((S, S)))

        h_SxE = jax.vmap(self.ln1)(x_SxE)
        h_SxE = self.attn(h_SxE, h_SxE, h_SxE, mask=mask_SxS)
        x_SxE = x_SxE + h_SxE

        h_SxE = jax.vmap(self.ln2)(x_SxE)
        h_SxE = jax.nn.gelu(jax.vmap(self.mlp_in)(h_SxE))
        h_SxE = jax.vmap(self.mlp_out)(h_SxE)
        x_SxE = x_SxE + h_SxE
        return x_SxE


class TinyGPT(eqx.Module):
    tok_emb: eqx.nn.Embedding
    pos_emb: jax.Array
    blocks: tuple
    ln_f: eqx.nn.LayerNorm
    lm_head: eqx.nn.Linear

    def __init__(self, vocab_size: int, embed_dim: int, num_heads: int,
                 num_layers: int, max_seq: int, *, key):
        keys = jax.random.split(key, num_layers + 2)
        self.tok_emb = eqx.nn.Embedding(vocab_size, embed_dim, key=keys[0])
        self.pos_emb = sinusoidal_positions(max_seq, embed_dim)
        self.blocks = tuple(
            Block(embed_dim, num_heads, key=keys[i + 1])
            for i in range(num_layers)
        )
        self.ln_f = eqx.nn.LayerNorm(embed_dim)
        self.lm_head = eqx.nn.Linear(embed_dim, vocab_size, key=keys[-1])

    def __call__(self, tokens_S: jax.Array, *, key=None) -> jax.Array:
        S = tokens_S.shape[0]
        x_SxE = jax.vmap(self.tok_emb)(tokens_S) + self.pos_emb[:S]
        for block in self.blocks:
            x_SxE = block(x_SxE, key=key)
        x_SxE = jax.vmap(self.ln_f)(x_SxE)
        logits_SxV = jax.vmap(self.lm_head)(x_SxE)
        return logits_SxV


def shard_model_and_batch(model, tokens_BxS, mesh: Mesh):
    """Replicate model arrays, shard tokens along mesh axis 'data'."""
    replicated = NamedSharding(mesh, P())
    batch_sh = NamedSharding(mesh, P('data', None))
    model = jax.tree.map(
        lambda x: jax.device_put(x, replicated) if eqx.is_array(x) else x,
        model,
    )
    tokens_BxS = jax.device_put(tokens_BxS, batch_sh)
    return model, tokens_BxS


def loss_fn(model, batch: dict) -> jax.Array:
    """Next-token cross-entropy. batch = {'tokens_BxS', 'targets_BxS'} with int dtype."""
    logits_BxSxV = jax.vmap(model)(batch['tokens_BxS'])
    loss_BxS = optax.softmax_cross_entropy_with_integer_labels(
        logits_BxSxV, batch['targets_BxS'],
    )
    return jnp.mean(loss_BxS)


def train_step(params, static, opt_state, batch, optimizer):
    """One DP train step. Caller is responsible for jit-ing with static_argnames=('static','optimizer')."""
    model = eqx.combine(params, static)
    loss, grads = eqx.filter_value_and_grad(loss_fn)(model, batch)
    grad_params, _ = eqx.partition(grads, eqx.is_array)
    updates, opt_state = optimizer.update(grad_params, opt_state, params)
    params = optax.apply_updates(params, updates)
    return params, opt_state, loss
