"""Chapter 2 reference solutions for the data-parallel exercises.

Used by tests/conftest.py to expose each function as a pytest fixture so the
same test bodies grade either (a) what the student wrote in the notebook, via
`judge.check(fn)`, or (b) this reference module, via `pytest tests/test_chapter_02.py`.

Students do not edit this file directly — they implement in the notebook.

Model components (Block, TinyGPT, sinusoidal_positions) are demos provided by
`src.common.models`, not exercises.
"""
from __future__ import annotations

import jax
import jax.numpy as jnp
import equinox as eqx
import optax
from jax.sharding import Mesh, PartitionSpec as P, NamedSharding


def shard_model_and_batch(model, tokens_BxS, mesh: Mesh):
    """Replicate model arrays, shard tokens along mesh axis 'data'."""
    replicated = NamedSharding(mesh, P())
    batch_sh = NamedSharding(mesh, P('data', None))
    model = jax.tree.map(
        lambda x: jax.device_put(x, replicated) if eqx.is_array(x) else x,
        model,
    )
    tokens_BxS = jax.device_put(tokens_BxS, batch_sh)
    return model, tokens_BxS


def loss_fn(model, batch: dict) -> jax.Array:
    """Next-token cross-entropy. batch = {'tokens_BxS', 'targets_BxS'} with int dtype."""
    logits_BxSxV = jax.vmap(model)(batch['tokens_BxS'])
    loss_BxS = optax.softmax_cross_entropy_with_integer_labels(
        logits_BxSxV, batch['targets_BxS'],
    )
    return jnp.mean(loss_BxS)


def train_step(params, static, opt_state, batch, optimizer):
    """One DP train step. Caller is responsible for jit-ing with static_argnames=('static','optimizer')."""
    model = eqx.combine(params, static)
    loss, grads = eqx.filter_value_and_grad(loss_fn)(model, batch)
    grad_params, _ = eqx.partition(grads, eqx.is_array)
    updates, opt_state = optimizer.update(grad_params, opt_state, params)
    params = optax.apply_updates(params, updates)
    return params, opt_state, loss
